# Generated by Django 4.1.4 on 2022-12-15 17:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import teasers.enums


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('description', models.TextField(verbose_name='Описание категории')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('active', models.BooleanField(default=True, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('slug',),
            },
        ),
        migrations.CreateModel(
            name='Price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(verbose_name='Цена')),
                ('start', models.DateField(verbose_name='Дата начала действия')),
                ('end', models.DateField(verbose_name='Дата окончания действия')),
                ('current', models.BooleanField(default=True, verbose_name='Последняя версия')),
            ],
            options={
                'verbose_name': 'Стоимость тизера',
                'verbose_name_plural': 'Цены тизеров',
                'ordering': ('-end',),
            },
        ),
        migrations.CreateModel(
            name='Teaser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Заголовок')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('status', models.CharField(choices=[('NEW', 'Новая'), ('REJECTED', 'Отклонена'), ('APPROVED', 'Оплачена')], default=teasers.enums.TeaserStatusEnum['NEW'], max_length=50, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teasers', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teasers', to='teasers.category', verbose_name='Категория')),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='teasers', to='teasers.price', verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Тизер',
                'verbose_name_plural': 'Тизеры',
                'ordering': ('-created_at',),
            },
        ),
    ]
